using System.Globalization;
using System.Text;

namespace ClrXray;

/// <summary>
/// Writes the picture a page shows. Plain SVG with no script and no external font, so it renders
/// on GitHub, in a static site and in a printed page without any of them agreeing about anything
/// else.
/// </summary>
internal static class DrawingSvg
{
    private const string Ink = "#1e1e1e";
    private const string Quiet = "#495057";
    private const string Line = "#868e96";

    internal static string Write(Drawing drawing, string sourceName)
    {
        var svg = new StringBuilder();
        var width = drawing.Width.ToString("0.##", CultureInfo.InvariantCulture);
        var height = drawing.Height.ToString("0.##", CultureInfo.InvariantCulture);

        svg.Append("<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"").Append(width)
           .Append("\" height=\"").Append(height)
           .Append("\" viewBox=\"0 0 ").Append(width).Append(' ').Append(height).Append("\">\n");

        svg.Append("  <style>\n")
           .Append("    text { font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif; }\n")
           .Append("    .heading { font-size: 15px; font-weight: 600; fill: ").Append(Ink).Append("; }\n")
           .Append("    .body { font-size: 13px; fill: ").Append(Quiet).Append("; }\n")
           .Append("    .cell-heading { font-size: 13px; font-weight: 600; fill: ").Append(Ink).Append("; }\n")
           .Append("    .cell-body { font-size: 11px; fill: ").Append(Quiet).Append("; }\n")
           .Append("    .title { font-size: 18px; font-weight: 700; fill: ").Append(Ink).Append("; }\n")
           .Append("    .edge { font-size: 12px; fill: ").Append(Quiet).Append("; paint-order: stroke; stroke: #ffffff; stroke-width: 4px; }\n")
           .Append("    .footer { font-size: 11px; fill: ").Append(Line).Append("; }\n")
           .Append("  </style>\n");

        svg.Append("  <defs>\n")
           .Append("    <marker id=\"head\" viewBox=\"0 0 10 10\" refX=\"9\" refY=\"5\" markerWidth=\"7\" markerHeight=\"7\" orient=\"auto-start-reverse\">\n")
           .Append("      <path d=\"M 0 0 L 10 5 L 0 10 z\" fill=\"").Append(Line).Append("\"/>\n")
           .Append("    </marker>\n")
           .Append("  </defs>\n");

        svg.Append("  <rect width=\"100%\" height=\"100%\" fill=\"#ffffff\"/>\n");

        if (drawing.Title.Length > 0)
        {
            svg.Append("  <text class=\"title\" x=\"24\" y=\"32\">").Append(Escape(drawing.Title)).Append("</text>\n");
        }

        foreach (var connector in drawing.Connectors)
        {
            Edge(svg, connector);
        }

        foreach (var shape in drawing.Shapes)
        {
            Box(svg, shape);
        }

        svg.Append("  <text class=\"footer\" x=\"24\" y=\"").Append((drawing.Height - 14).ToString("0.##", CultureInfo.InvariantCulture))
           .Append("\">Generated by xray from ").Append(Escape(sourceName)).Append(". Edit that file, not this one.</text>\n");

        svg.Append("</svg>\n");
        return svg.ToString();
    }

    private static void Box(StringBuilder svg, Shape shape)
    {
        var fill = shape.Kind switch
        {
            ShapeKind.Note => "#fff9db",
            ShapeKind.Cell => "#f8f9fa",
            _ => "#ffffff",
        };

        var dash = shape.Kind == ShapeKind.Note ? " stroke-dasharray=\"6 4\"" : string.Empty;

        svg.Append("  <rect x=\"").Append(N(shape.X)).Append("\" y=\"").Append(N(shape.Y))
           .Append("\" width=\"").Append(N(shape.Width)).Append("\" height=\"").Append(N(shape.Height))
           .Append("\" rx=\"6\" fill=\"").Append(fill).Append("\" stroke=\"").Append(Ink).Append("\" stroke-width=\"1.5\"").Append(dash).Append("/>\n");

        var cell = shape.Kind == ShapeKind.Cell;
        var headingHeight = cell ? 17.0 : 20.0;
        var bodyHeight = cell ? 15.0 : 17.0;
        var total = 0.0;
        for (var i = 0; i < shape.Lines.Count; i++)
        {
            total += shape.IsHeading(i) ? headingHeight : bodyHeight;
        }

        var baseline = shape.CentreY - (total / 2) + (cell ? 12 : 14);

        for (var i = 0; i < shape.Lines.Count; i++)
        {
            var heading = shape.IsHeading(i);
            var style = heading
                ? (cell ? "cell-heading" : "heading")
                : (cell ? "cell-body" : "body");

            svg.Append("  <text class=\"").Append(style).Append("\" text-anchor=\"middle\" x=\"").Append(N(shape.CentreX))
               .Append("\" y=\"").Append(N(baseline)).Append("\">").Append(Escape(shape.Lines[i])).Append("</text>\n");

            baseline += heading ? headingHeight : bodyHeight;
        }
    }

    private static void Edge(StringBuilder svg, Connector connector)
    {
        var (x1, y1, x2, y2) = Anchors(connector.From, connector.To);

        svg.Append("  <line x1=\"").Append(N(x1)).Append("\" y1=\"").Append(N(y1))
           .Append("\" x2=\"").Append(N(x2)).Append("\" y2=\"").Append(N(y2))
           .Append("\" stroke=\"").Append(Line).Append("\" stroke-width=\"1.5\" marker-end=\"url(#head)\"/>\n");

        if (connector.Label.Length > 0)
        {
            svg.Append("  <text class=\"edge\" text-anchor=\"middle\" x=\"").Append(N((x1 + x2) / 2))
               .Append("\" y=\"").Append(N(((y1 + y2) / 2) - 6)).Append("\">").Append(Escape(connector.Label)).Append("</text>\n");
        }
    }

    /// <summary>
    /// Picks which side of each box the line leaves and arrives at.
    /// </summary>
    /// <remarks>
    /// The choice is made on the gap between the two boxes rather than on the distance between
    /// their centres, and the difference matters. Two boxes in different rows, far apart
    /// sideways, have a wide gap below one and no gap beside them, and an arrow that leaves
    /// sideways there crosses back over itself. Measuring the gap sends it down instead, which is
    /// what a person drawing the same picture would do.
    /// </remarks>
    internal static (double X1, double Y1, double X2, double Y2) Anchors(Shape from, Shape to)
    {
        var dx = to.CentreX - from.CentreX;
        var dy = to.CentreY - from.CentreY;

        var sideways = Gap(from.X, from.Width, to.X, to.Width);
        var upright = Gap(from.Y, from.Height, to.Y, to.Height);

        if (sideways > upright)
        {
            var right = dx > 0;
            return (
                right ? from.X + from.Width : from.X,
                from.CentreY,
                right ? to.X : to.X + to.Width,
                to.CentreY);
        }

        var down = dy > 0;
        return (
            from.CentreX,
            down ? from.Y + from.Height : from.Y,
            to.CentreX,
            down ? to.Y : to.Y + to.Height);
    }

    /// <summary>The clear space between two spans on one axis, or zero when they overlap.</summary>
    private static double Gap(double a, double aSize, double b, double bSize)
    {
        if (b > a + aSize)
        {
            return b - (a + aSize);
        }

        if (a > b + bSize)
        {
            return a - (b + bSize);
        }

        return 0;
    }

    private static string N(double value) => value.ToString("0.##", CultureInfo.InvariantCulture);

    private static string Escape(string text) => text
        .Replace("&", "&amp;", StringComparison.Ordinal)
        .Replace("<", "&lt;", StringComparison.Ordinal)
        .Replace(">", "&gt;", StringComparison.Ordinal)
        .Replace("\"", "&quot;", StringComparison.Ordinal);
}
